/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Banco;
import javax.swing.JOptionPane;
import modelo.Login;

/**
 *
 * @author Diego
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenhapass = new javax.swing.JPasswordField();
        btnSair = new javax.swing.JButton();
        btncadLogin = new javax.swing.JButton();
        btnAcessar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 140, 40));

        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 270, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 66, 110, -1));
        getContentPane().add(txtSenhapass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 270, 40));

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Exit25.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 100, 50));

        btncadLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncadLogin.setForeground(new java.awt.Color(255, 0, 0));
        btncadLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Salvar25.png"))); // NOI18N
        btncadLogin.setText("Cadastrar");
        btncadLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btncadLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 150, 50));

        btnAcessar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAcessar1.setForeground(new java.awt.Color(255, 0, 0));
        btnAcessar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/HomeIcon.png"))); // NOI18N
        btnAcessar1.setText("Acessar");
        btnAcessar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcessar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/agenda.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncadLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadLoginActionPerformed
       
    }//GEN-LAST:event_btncadLoginActionPerformed

    private void btnAcessar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessar1ActionPerformed
      try{
          Banco b = new Banco();
          Login l = new Login();
          l.setNomeUsuario(txtLogin.getText());
          l.setSenha(txtSenhapass.getText());
          boolean resposta = b.ValidarLogin(l.getNomeUsuario(), l.getSenha());
          if(resposta == true){
              JOptionPane.showMessageDialog(null, "Login realizado com sucesso!!!");
              new TelaPrincipal().setVisible(true);
              this.dispose();
          }else {
              JOptionPane.showMessageDialog(null, "Login não realizado!\n Favor conferir o login e senha se esta´"
                      + "digitado corretamente");
              txtLogin.setText("");
              txtSenhapass.setText("");
              txtLogin.requestFocus();
              
          }
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_btnAcessar1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar1;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btncadLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenhapass;
    // End of variables declaration//GEN-END:variables
}
